# Add 'size: tiny' to any changes of at most 4 lines
'size: tiny':
  max: 4

# Add 'size: small' to any changes between 5 and 10 lines
'size: small':
  min: 5
  max: 10

# Add 'size: medium' to any changes between 11 and 100 lines
'size: medium':
  min: 11
  max: 100

# Add 'size: large' to any changes between 101 and 500 lines
'size: large':
  min: 101
  max: 500

# Add 'size: huge' to any changes of more than 500 lines
'size: huge':
  min: 501
