name: Charting Issue
description: Report an issue with the placement of notes in the game.
labels: ["type: charting issue", "status: pending triage"]
title: "Charting Issue: "
body:
  - type: markdown
    attributes:
      value: "# PLEASE READ THE [CONTRIBUTING GUIDE](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md) BEFORE OPENING ISSUES!"
      
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        - label: I have read the [Contributing Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md)
        - label: I have checked the Issues/Discussions pages to see if my issue has already been reported
        - label: I have properly titled my issue

  - type: dropdown
    attributes:
      label: Platform
      description: Which platform are you playing on?
      options:
        - Newgrounds (Web/HTML5)
        - Itch.io (Web/HTML5)
        - Itch.io (Downloadable Build) - Windows
        - Itch.io (Downloadable Build) - MacOS
        - Itch.io (Downloadable Build) - Linux
        - Compiled from GitHub Source Code
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Browser
      description: (Web/HTML5 users only) Which browser are you playing on?
      options:
        - Google Chrome
        - Microsoft Edge
        - Firefox
        - Opera
        - Safari
        - Other (Specify in Description field)

  - type: input
    attributes:
      label: Version
      description: Which version are you playing on? The game version is in the bottom left corner of the main menu. 
      placeholder: ex. 0.6.4
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: "## Describe the charting issue(s)."

  - type: markdown
    attributes:
      value: "### Please do not report issues from other engines. These must be reported in their respective repositories."

  - type: textarea
    attributes:
      label: Location
      description: Where did you find the issue(s)? Include the name of the song, the variation, the difficulty, the time/section of the song, and any images or videos.
      placeholder: ex. Cocoa Erect on Erect/Nightmare difficulties at Section 30
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Why do you believe this is an issue? Is a note at the wrong time, a hold note too short/long, or something else?
      placeholder: Describe the charting issue(s) here...
    validations:
      required: true
