function start() 
    makeSprite("stageback", "bg", true, true, true)
    setActorScrollFactor(0.9, 0.9, "bg")
    makeSprite("stagefront", "stageFront", true, true, true)
    setActorScrollFactor(1.3, 1.3, "stageFront")
    setActorScale(1.1, "stageFront")
    makeSprite("stagecurtains", "stageCurtains", true, true, true)
    setActorScale(0.9, "stageCurtains")
    setActorScrollFactor(1.3, 1.3, "stageCurtains")
end