name: Multiplatform Game Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Haxelibs
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install hxp
          haxelib run lime setup

      - name: Compile Game
        run: |
          haxelib run lime build ${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'ubuntu-latest' && 'linux' || 'mac' }} -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Funkin-${{ matrix.os }}
          path: export/release/**

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Haxelibs & Setup Android
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install hxp
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK_ROOT $ANDROID_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Compile APK
        run: haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Funkin-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
